# Generated by Django 4.1.6 on 2023-12-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IncomeApp', '0002_alter_expense_name_alter_income_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
    ]
